allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }

    configurations.all {
        resolutionStrategy {
            force 'com.github.teamnewpipe:NewPipeExtractor:v0.26.2'
        }
    }
}

// Workaround for Flutter Gradle Plugin bug on Windows paths with spaces
def buildPath = new File(rootProject.projectDir.parentFile, "build").absolutePath
if (System.getProperty("os.name").toLowerCase().contains("windows") && buildPath.contains(" ")) {
    new File(buildPath).mkdirs()
    def process = "cmd /c for %I in (\"${buildPath}\") do @echo %~sI".execute()
    process.waitFor()
    rootProject.buildDir = process.text.trim()
} else {
    rootProject.buildDir = '../build'
}

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}